import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'uz' | 'ru';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Hero section
    'hero.title': 'Get Into Your',
    'hero.title.accepted': 'Dream University!',
    'hero.subtitle': 'Get UNLOCK UZBEKISTAN\'s most comprehensive admission package. Work with 3 specialists: Strategist, Essay Mentor, and Helper. Choose our university selection or get 100% money-back guarantee.',
    'hero.cta': 'Apply to Accepted',
    'hero.consultation': 'Schedule Consultation',
    'hero.feature1': '3 specialists for each student',
    'hero.feature2': '100% Money-Back Guarantee*',
    'hero.feature3': 'Complete application assistance',
    'hero.feature4': 'August 1st to Final Decision',
    'hero.card.text': 'Applications start',
    'hero.card.cta': 'Get Started',
    
    // Contact form
    'contact.title.accepted': 'ACCEPTED',
    'contact.title.text': 'Apply Now',
    'contact.subtitle': 'Ready to work with 3 specialists to get into your dream university? Start your application today or schedule a consultation.',
    'contact.form.title': 'Apply to Accepted Program',
    'contact.form.name': 'Name',
    'contact.form.surname': 'Surname',
    'contact.form.email': 'Email',
    'contact.form.phone': 'Phone Number',
    'contact.form.major': 'Major or Areas Interested',
    'contact.form.education': 'Current Education Status',
    'contact.form.universities': 'List 5 Universities You Want to Get Into',
    'contact.form.contribution': 'Annual Contribution Towards University',
    'contact.form.comment': 'Additional Comment',
    'contact.form.submit': 'Submit Application',
    'contact.form.submitting': 'Submitting...',
    'contact.form.placeholder.name': 'Your first name',
    'contact.form.placeholder.surname': 'Your last name',
    'contact.form.placeholder.email': 'your.email@example.com',
    'contact.form.placeholder.phone': '+998 90 123 45 67',
    'contact.form.placeholder.major': 'e.g., Computer Science, Medicine, Business',
    'contact.form.placeholder.education': 'e.g., Grade 11, High School Graduate, University Transfer',
    'contact.form.placeholder.universities': 'Please list your top 5 university choices...',
    'contact.form.placeholder.contribution': 'e.g., $50,000, Full scholarship needed, etc.',
    'contact.form.placeholder.comment': 'Tell us about your academic background, extracurricular activities, and goals...',
    'contact.info.location.title': 'Our Location',
    'contact.info.location.address': 'Tashkent, Uzbekistan',
    'contact.info.location.description': 'UNLOCK UZBEKISTAN headquarters. We serve students nationwide who want to apply to universities in the US, UK, Europe, and Asia.',
    'contact.info.phone.title': 'Phone',
    'contact.info.phone.number': '+998 90 123 45 67',
    'contact.info.phone.description': 'Call us to schedule your Accepted program consultation.',
    'contact.info.email.title': 'Email',
    'contact.info.email.address': 'accepted@unlocku.uz',
    'contact.info.email.description': 'Send us your application questions via email and we\'ll respond within 24 hours.',
    'contact.info.hours.title': 'Working Hours',
    'contact.info.hours.time': 'Mon - Fri: 9:00 - 18:00',
    'contact.info.hours.description': 'We are available during business hours for consultations and application assistance.',
    'contact.cta.title': 'Ready to Get Accepted?',
    'contact.cta.description': 'Applications start August 1st, 2025. Get priority consultation with early advice.',
    'contact.cta.button': 'Get Priority Access',
    'contact.form.error.required': 'Please fill in all required fields.',
    'contact.form.error.submit': 'Error submitting application. Please try again.',
    'contact.form.success.title': 'Success!',
    'contact.form.success.description': 'Your application has been submitted! We will contact you within 24 hours.',
    
    // Navigation
    'nav.about': 'About',
    'nav.courses': 'Courses',
    'nav.testimonials': 'Success Stories',
    'nav.faq': 'FAQ',
    'nav.contact': 'Contact',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    
    // About section
    'about.title': '',
    'about.title.highlight': 'UNLOCK UZBEKISTAN',
    'about.subtitle': 'Founded in Tashkent in 2022. We started by podcasting with Uzbek students who got into Ivy League schools. Now we offer comprehensive admission help through our "Accepted" program with 50,000+ viewers.',
    'about.values.mission.title': 'Our Mission',
    'about.values.mission.description': 'To help Uzbek students with expert guidance and proven strategies for international university admissions.',
    'about.values.story.title': 'Our Story',
    'about.values.story.description': 'Starting with podcasts featuring students admitted to Ivy League universities, we now support students with full admission services.',
    'about.values.impact.title': 'Community Impact',
    'about.values.impact.description': 'Over 50,000 viewers trust our content. We\'ve helped students get into Chicago, Duke, Carnegie Mellon Qatar, and NYU.',
    'about.values.approach.title': 'Our Approach',
    'about.values.approach.description': 'Three specialists for each student: Strategist for planning, Essay Mentor for writing, and Helper for technical support.',
    'about.why.title': 'Why Choose Accepted?',
    'about.why.expert.title': 'Expert Team',
    'about.why.expert.description': 'Work with 3 specialists - Strategist, Essay Mentor, and Helper for comprehensive coverage.',
    'about.why.system.title': 'Dual-Track System',
    'about.why.system.description': 'Choose your universities or trust our selection with 100% money-back guarantee.',
    'about.why.support.title': 'Complete Support',
    'about.why.support.description': 'From August 1st to final decisions, covering all 16 checklist items.',
    'about.why.success.title': 'Proven Success',
    'about.why.success.description': 'Students have been accepted to top universities like UChicago, Duke, Carnegie Mellon Qatar.',
    'about.stats.viewers': 'Podcast Viewers',
    'about.stats.sat': 'Average SAT Score',
    'about.stats.founded': 'Founded in Tashkent',
    
    // Testimonials section
    'testimonials.title': 'Success',
    'testimonials.title.highlight': 'Stories',
    'testimonials.subtitle': 'Hear from our students who transformed their educational paths and achieved their dreams through our Accepted program.',
    
    // FAQ section
    'faq.title': 'Frequently',
    'faq.title.highlight': 'Asked Questions',
    'faq.subtitle': 'Answers to the most common questions about our Accepted program.',
    'faq.q1.question': 'Who can join the Accepted program?',
    'faq.q1.answer': 'Our program is open to all students who are serious about higher education. Regardless of whether you\'re from rural or urban areas, our program helps you succeed with any background.',
    'faq.q2.question': 'How is this different from free resources?',
    'faq.q2.answer': 'We believe in free education, but the Accepted program offers personal mentoring, live interactive sessions, comprehensive study materials, practice tests, and individual guidance not found in free resources.',
    'faq.q3.question': 'How long does it take to complete the program?',
    'faq.q3.answer': 'The complete program lasts 16 weeks, with 3 sessions per week. Each session builds on the previous one and ensures complete preparation for your admission goals.',
    'faq.q4.question': 'Are there payment plans or scholarships?',
    'faq.q4.answer': 'Yes! We offer flexible payment plans and need-based scholarships for students who demonstrate financial need. Our goal is to make quality education accessible to everyone.',
    'faq.q5.question': 'What if I\'m not satisfied with the program?',
    'faq.q5.answer': 'We offer a 30-day money-back guarantee. If you\'re completely unsatisfied with the program within the first 30 days, we\'ll provide a full refund with no questions asked.',
    'faq.q6.question': 'Will I get help after the program ends?',
    'faq.q6.answer': 'Absolutely! You\'ll have lifetime access to our alumni network, course materials, and can schedule additional mentoring sessions. We\'re committed to your long-term success.',
    'faq.q7.question': 'How do live sessions work?',
    'faq.q7.answer': 'Live sessions are conducted online through our learning platform. They\'re interactive, allowing you to ask questions in real-time. All sessions are recorded so you can review them later.',
    'faq.q8.question': 'What technology do I need for the program?',
    'faq.q8.answer': 'You\'ll need a computer or tablet with internet connection. Our platform works on all modern browsers and we provide technical support to ensure your full participation.',
    
    // Course Details section
    'course.title': 'Complete Admission Package',
    'course.title.highlight': 'Accepted',
    'course.subtitle': 'Our most comprehensive admission program. Work with 3 specialists from August 1st to final decisions. Choose our university selection for 100% money-back guarantee.',
    'course.team.title': 'Your Expert Team',
    'course.team.strategist': 'Strategist',
    'course.team.strategist.description': 'Manages application strategy, creates college lists, plans timelines, helps with positioning and activities.',
    'course.team.essay': 'Essay Mentor',
    'course.team.essay.description': 'Helps develop, draft, and edit ideas to make essays clear, personal, and impactful.',
    'course.team.helper': 'Helper',
    'course.team.helper.description': 'Assists with application forms, financial documents, scheduling, reminders, and other technical tasks.',
    'course.details.title': 'Program Details',
    'course.details.duration': 'Duration',
    'course.details.duration.value': 'Aug 1 - final decisions',
    'course.details.team': 'Team Size',
    'course.details.team.value': '3 specialists per student',
    'course.details.universities': 'Universities',
    'course.details.universities.value': '5 target schools',
    'course.details.support': 'Support Type',
    'course.details.support.value': 'Complete application',
    'course.details.checklist': '16-item student checklist:',
    'course.pricing.badge': 'Applications Open',
    'course.pricing.title': 'Accepted Program',
    'course.pricing.contact': 'Contact',
    'course.pricing.price': 'for Pricing',
    'course.pricing.custom': 'Customized to your needs',
    'course.pricing.apply': 'Apply Now',
    'course.pricing.consultation': 'Schedule Consultation',
    'course.pricing.guarantee': '🛡️ 100% money-back guarantee available • Premium support',
    
    // Footer section
    'footer.description': 'UNLOCK UZBEKISTAN - organization helping Uzbek students get into international universities. Our goal is to help every student achieve their dreams.',
    'footer.quicklinks': 'Quick Links',
    'footer.quicklinks.about': 'About Us',
    'footer.quicklinks.accepted': 'Accepted Program',
    'footer.quicklinks.testimonials': 'Success Stories',
    'footer.quicklinks.contact': 'Contact',
    'footer.quicklinks.blog': 'Blog',
    'footer.support': 'Support',
    'footer.support.center': 'Help Center',
    'footer.support.portal': 'Student Portal',
    'footer.support.payments': 'Payment Methods',
    'footer.support.scholarships': 'Scholarships',
    'footer.support.technical': 'Technical Support',
    'footer.newsletter': 'Stay Updated',
    'footer.newsletter.description': 'Subscribe to be the first to know about programs and educational opportunities.',
    'footer.newsletter.placeholder': 'Your email address',
    'footer.newsletter.spam': 'No spam. Unsubscribe anytime.',
    'footer.copyright': '© 2024 Unlock Uzbekistan. All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Use',
    'footer.cookies': 'Cookie Policy',

    // Audience Selector
    'welcomeTitle': 'Welcome',
    'audienceSelectorSubtitle': 'Choose the portal that suits you best',
    'studentsTitle': 'Students',
    'studentsDescription': 'Information and resources for students',
    'studentFeature1': 'Personal guidance',
    'studentFeature2': 'University programs',
    'studentFeature3': 'Application assistance',
    'studentFeature4': 'Test preparation',
    'enterStudentPortal': 'Enter Student Portal',
    'parentsTitle': 'Parents',
    'parentsDescription': 'Guidance and support for parents',
    'parentFeature1': 'Parent guide',
    'parentFeature2': 'Financial planning',
    'parentFeature3': 'Family support',
    'parentFeature4': 'Expert consultations',
    'enterParentPortal': 'Enter Parent Portal',
    'notSureText': 'Not sure? View general information',
    'viewGeneralInfo': 'View General Information',

    // Student-specific content
    'studentHeroTitle': 'Your Future Starts Here',
    'studentHeroSubtitle': 'Personalized guidance for admission to the world\'s top universities',
    'studentBenefit1': 'Expert guidance',
    'studentBenefit2': 'Test preparation',
    'studentBenefit3': 'Global opportunities',
    'studentBenefit4': 'Community support',
    'explorePrograms': 'Explore Programs',
    'getPersonalConsultation': 'Get Consultation',
    'studentSuccessRate': '95% admission success',
    'studentSuccessRateSubtext': 'Our students get into top universities',

    // Parent-specific content
    'parentHeroTitle': 'Support Your Child\'s Future',
    'parentHeroSubtitle': 'Comprehensive guidance for parents in the international education journey',
    'parentBenefit1': 'Family support',
    'parentBenefit2': 'Financial planning',
    'parentBenefit3': 'Expert consultations',
    'parentBenefit4': 'Progress tracking',
    'getParentGuide': 'Get Parent Guide',
    'speakWithExpert': 'Speak with Expert',
    'parentSuccessMetric': '500+ families trust us',
    'parentSuccessMetricSubtext': 'Helping families since 2020',

    // Additional common translations
    'learnMore': 'Learn More',
    'scheduleConsultation': 'Schedule Consultation',
    'downloadGuide': 'Download Guide',
    'watchWebinar': 'Watch Webinar',
    'accessLibrary': 'Access Library',
    'joinCommunity': 'Join Community',
    'needPersonalizedHelp': 'Need personalized help?',
    'personalizedHelpDescription': 'Schedule a one-on-one consultation with our experts',
    'downloadCompleteGuide': 'Download Complete Guide',
    'startChat': 'Start Chat',
    'scheduleCall': 'Schedule Call',
    'bookSession': 'Book Session',
    'joinGroup': 'Join Group',
    'emergencySupport': 'Emergency Support',
    'emergencySupportDesc': 'Urgent help available 24/7 for critical questions',
    'emergencyContact': 'Emergency Contact',

    // Student About section
    'studentAboutTitle': 'Why Students Choose Us',
    'studentAboutSubtitle': 'We provide everything needed for successful university admission',
    'studentAboutFeature1Title': 'Expert Guidance',
    'studentAboutFeature1Desc': 'Personal mentorship from experienced consultants',
    'studentAboutFeature2Title': 'Personalized Approach',
    'studentAboutFeature2Desc': 'Program adapts to your goals and needs',
    'studentAboutFeature3Title': 'Community Support',
    'studentAboutFeature3Desc': 'Join a network of successful students',
    'studentAboutFeature4Title': 'Guaranteed Results',
    'studentAboutFeature4Desc': '95% of our students get into target universities',

    // Student Programs section
    'studentProgramsTitle': 'Our Student Programs',
    'studentProgramsSubtitle': 'Choose the program that fits you best',
    'studentProgram1Title': 'Basic Program',
    'studentProgram1Desc': 'Foundation for international university admission',
    'studentProgram1Duration': '3 months',
    'studentProgram1GroupSize': 'Up to 10 people',
    'studentProgram1Level': 'Beginner',
    'studentProgram1Feature1': 'University and major selection',
    'studentProgram1Feature2': 'Language test preparation',
    'studentProgram1Feature3': 'Personal statement writing',
    'studentProgram1Feature4': 'Application submission',
    'studentProgram2Title': 'Advanced Program',
    'studentProgram2Desc': 'Comprehensive preparation with personal mentorship',
    'studentProgram2Duration': '6 months',
    'studentProgram2GroupSize': 'Up to 5 people',
    'studentProgram2Level': 'Intermediate',
    'studentProgram2Feature1': 'Personal mentor',
    'studentProgram2Feature2': 'SAT/TOEFL preparation',
    'studentProgram2Feature3': 'Achievement portfolio',
    'studentProgram2Feature4': 'Mock interviews',
    'studentProgram3Title': 'Premium Program',
    'studentProgram3Desc': 'Complete package for top university admission',
    'studentProgram3Duration': '12 months',
    'studentProgram3GroupSize': 'Individual',
    'studentProgram3Level': 'Advanced',
    'studentProgram3Feature1': 'Team of 3 experts',
    'studentProgram3Feature2': 'Admission guarantee',
    'studentProgram3Feature3': 'Scholarship preparation',
    'studentProgram3Feature4': '24/7 support',

    // Student Resources section
    'studentResourcesTitle': 'Student Resources',
    'studentResourcesSubtitle': 'All necessary materials in one place',
    'studentResource1Title': 'Admission Guide',
    'studentResource1Desc': 'Step-by-step application instructions',
    'studentResource2Title': 'Video Lessons',
    'studentResource2Desc': 'Educational materials from experts',
    'studentResource3Title': 'Resource Library',
    'studentResource3Desc': 'Knowledge base on universities and programs',
    'studentResource4Title': 'Student Community',
    'studentResource4Desc': 'Connect with peers and alumni',

    // Parent About section
    'parentAboutTitle': 'How We Support Parents',
    'parentAboutSubtitle': 'We understand the importance of family support in education',
    'parentAboutFeature1Title': 'Family Approach',
    'parentAboutFeature1Desc': 'Work with family as a unified team',
    'parentAboutFeature2Title': 'Process Transparency',
    'parentAboutFeature2Desc': 'Regular updates on your child\'s progress',
    'parentAboutFeature3Title': 'Financial Planning',
    'parentAboutFeature3Desc': 'Help planning education expenses',
    'parentAboutFeature4Title': 'Emotional Support',
    'parentAboutFeature4Desc': 'Psychological help for family at all stages',

    // Parent Guide section
    'parentGuideTitle': 'Parent Guide',
    'parentGuideSubtitle': 'Step-by-step plan to support your child',
    'parentGuideStep1Title': 'Planning and Preparation',
    'parentGuideStep1Desc': 'Define goals and create action plan',
    'parentGuideStep1Duration': '1-2 months',
    'parentGuideStep1Task1': 'Discuss goals with child',
    'parentGuideStep1Task2': 'Research universities',
    'parentGuideStep1Task3': 'Financial planning',
    'parentGuideStep2Title': 'Academic Preparation',
    'parentGuideStep2Desc': 'Support your child in academic process',
    'parentGuideStep2Duration': '6-12 months',
    'parentGuideStep2Task1': 'Monitor academic performance',
    'parentGuideStep2Task2': 'Test preparation',
    'parentGuideStep2Task3': 'Develop extracurricular activities',
    'parentGuideStep3Title': 'Application Process',
    'parentGuideStep3Desc': 'Help with application submission',
    'parentGuideStep3Duration': '3-6 months',
    'parentGuideStep3Task1': 'Gather required documents',
    'parentGuideStep3Task2': 'Review applications',
    'parentGuideStep3Task3': 'Meet deadlines',
    'parentGuideStep4Title': 'Decision Making',
    'parentGuideStep4Desc': 'Support in choosing best offer',
    'parentGuideStep4Duration': '1-3 months',
    'parentGuideStep4Task1': 'Analyze offers',
    'parentGuideStep4Task2': 'Financial calculations',
    'parentGuideStep4Task3': 'Final decision',
    'parentGuideCallToAction': 'Get Complete Guide',
    'parentGuideCallToActionDesc': 'Download detailed plan or schedule expert consultation',

    // Parent Support section
    'parentSupportTitle': 'Parent Support',
    'parentSupportSubtitle': 'We\'re always ready to help you and your child',
    'parentSupport1Title': 'Online Chat',
    'parentSupport1Desc': 'Quick answers to your questions',
    'parentSupport1Availability': '24/7',
    'parentSupport2Title': 'Phone Consultations',
    'parentSupport2Desc': 'Personal conversations with experts',
    'parentSupport2Availability': 'Mon-Fri 9:00-18:00',
    'parentSupport3Title': 'Video Consultations',
    'parentSupport3Desc': 'Detailed video call meetings',
    'parentSupport3Availability': 'By appointment',
    'parentSupport4Title': 'Group Meetings',
    'parentSupport4Desc': 'Connect with other parents',
    'parentSupport4Availability': 'Weekly',
  },
  uz: {
    // Hero section
    'hero.title': 'Orzungizdagi',
    'hero.title.accepted': 'Universitetga Kiring!',
    'hero.subtitle': '"UNLOCK UZBEKISTAN" o\'zining "Accepted" dasturi orqali universitetga kirish bo\'yicha keng qamrovli yo\'l-yo\'riqlar taqdim etadi. Dasturda siz uch mutaxassis — strateg, insho yozish bo\'yicha mentor hamda qabul jarayonida ko\'maklashuvchi xodim bilan ishlash imkoniyatiga ega bo\'lasiz. Biz tanlagan universitetlarga o\'qishga kira olmasangiz, to\'langan mablag\' 100% kafolat bilan qaytariladi.',
    'hero.cta': '"Accepted" dasturi haqida',
    'hero.consultation': 'Ariza topshirish',
    'hero.feature1': 'Har bir talaba uchun uch nafar mutaxassis jalb qilinadi.',
    'hero.feature2': 'Dastur uchun to\'langan mablag\' 100% qaytariladi.',
    'hero.feature3': 'Ariza topshirish jarayonining boshidan oxirigacha yordam ko\'rsatiladi.',
    'hero.feature4': 'Dastur Avgustdan toki qabul natijalari chiqishiga qadar davom etadi',
    'hero.card.text': 'Arizalar 1-Avgustga qadar qabul qilinadi',
    'hero.card.cta': 'Ariza topshirish',
    
    // Contact form
    'contact.title.accepted': 'ACCEPTED',
    'contact.title.text': 'ga ariza ber',
    'contact.subtitle': '3 ta mutaxassis bilan ishlab orzuing universitetga kirishga tayyormisan? Bugun arizangni boshla yoki maslahat vaqti belgilay.',
    'contact.form.title': 'Accepted dasturiga ariza ber',
    'contact.form.name': 'Ism',
    'contact.form.surname': 'Familiya',
    'contact.form.email': 'Email',
    'contact.form.phone': 'Telefon raqami',
    'contact.form.major': 'Qiziqish sohasi',
    'contact.form.education': "Hozirgi ta'lim holati",
    'contact.form.universities': 'Kirmoqchi bo\'lgan 5 ta universitet ro\'yxati',
    'contact.form.contribution': 'Yillik moliyaviy hissa',
    'contact.form.comment': "Qo'shimcha izoh",
    'contact.form.submit': 'Arizani yuborish',
    'contact.form.submitting': 'Yuborilmoqda...',
    'contact.form.placeholder.name': 'Ismingiz',
    'contact.form.placeholder.surname': 'Familiyangiz',
    'contact.form.placeholder.email': 'your.email@example.com',
    'contact.form.placeholder.phone': '+998 90 123 45 67',
    'contact.form.placeholder.major': 'masalan: Informatika, Tibbiyot, Biznes',
    'contact.form.placeholder.education': 'masalan: 11-sinf, Maktabni bitirgan, Universitetdan o\'tish',
    'contact.form.placeholder.universities': 'Top 5 ta universitet tanlovingizni yozing...',
    'contact.form.placeholder.contribution': 'masalan: $50,000, To\'liq stipendiya kerak, va h.k.',
    'contact.form.placeholder.comment': 'O\'qish tarixingiz, qo\'shimcha faoliyatingiz va maqsadlaringiz haqida ayting...',
    'contact.info.location.title': 'Bizning joylashuvimiz',
    'contact.info.location.address': 'Toshkent, O\'zbekiston',
    'contact.info.location.description': 'UNLOCK UZBEKISTAN bosh ofisi. Biz AQSh, Buyuk Britaniya, Yevropa va Osiyodagi universitetlarga ariza berishni istagan butun mamlakat bo\'ylab talabalarga xizmat ko\'rsatamiz.',
    'contact.info.phone.title': 'Telefon',
    'contact.info.phone.number': '+998 90 123 45 67',
    'contact.info.phone.description': 'Accepted dasturi maslahatini rejalashtirish uchun bizga qo\'ng\'iroq qiling.',
    'contact.info.email.title': 'Email',
    'contact.info.email.address': 'accepted@unlocku.uz',
    'contact.info.email.description': 'Ariza savollaringizni bizga emailda yuboring va biz 24 soat ichida javob beramiz.',
    'contact.info.hours.title': 'Ish vaqti',
    'contact.info.hours.time': 'Dush - Jum: 9:00 - 18:00',
    'contact.info.hours.description': 'Biz ish vaqtida maslahat va ariza yordami uchun mavjudmiz.',
    'contact.cta.title': 'Qabul bo\'lishga tayyormisan?',
    'contact.cta.description': '2025-yil 1-avgustdan boshlab arizalar. Erta maslahat bilan ustuvor yo\'lni ol.',
    'contact.cta.button': 'Ustuvor yo\'lni ol',
    'contact.form.error.required': 'Iltimos, barcha majburiy maydonlarni to\'ldiring.',
    'contact.form.error.submit': 'Arizani yuborishda xatolik yuz berdi. Qaytadan urinib ko\'ring.',
    'contact.form.success.title': 'Muvaffaqiyat!',
    'contact.form.success.description': 'Arizangiz yuborildi! Biz 24 soat ichida sizga aloqaga chiqamiz.',
    
    // Navigation
    'nav.about': 'Biz haqimizda',
    'nav.courses': 'Kurslar',
    'nav.testimonials': 'Muvaffaqiyat hikoyalari',
    'nav.faq': 'Savollar',
    'nav.contact': 'Aloqa',
    
    // Common
    'common.loading': 'Yuklanmoqda...',
    'common.error': 'Xatolik',
    'common.success': 'Muvaffaqiyat',
    
    // About section
    'about.title': '',
    'about.title.highlight': 'UNLOCK UZBEKISTAN',
    'about.subtitle': '2022-yilda Toshkentda tashkil etilgan. Biz Ivy League maktablariga kirgan o\'zbek talabalar bilan podcast qilishdan boshladik. Endi 50,000+ ko\'ruvchi bilan "Accepted" dasturi orqali to\'liq qabul yordamini taklif qilamiz.',
    'about.values.mission.title': 'Maqsadimiz',
    'about.values.mission.description': 'O\'zbekistonlik talabalarga xalqaro universitetlarga kirish jarayonida samarali maslahatlar va usullar orqali ko\'maklashish.',
    'about.values.story.title': 'Hikoyamiz',
    'about.values.story.description': 'Top universitetlarga qabul qilingan talabalar bilan podkastlar olib borib, hozirda qolganlarga ham ushbu jarayonda yordam bermoqdamiz.',
    'about.values.impact.title': 'Jamiyatga ta\'sir',
    'about.values.impact.description': '50,000dan ortiq kuzatuvchi biladiki, biz hozirgacha talabalarga Chicago, Duke, Carnegie Mellon Qatar va NYU universitetlariga kirishda yordam berdik.',
    'about.values.approach.title': 'Yondashuvimiz',
    'about.values.approach.description': 'Har bir talaba uchun uch mutaxassis: rejalashtirish uchun strateg, insho yozish bo\'yicha mentor va arizangizning qolgan qismini tekshirish uchun qabul bo\'yicha tajribali inson.',
    'about.why.title': 'Nega "Accepted"ni tanlash kerak?',
    'about.why.expert.title': 'Mutaxassis Jamoa',
    'about.why.expert.description': '3 ta mutaxassis bilan ishlang - Strategist, Insho Mentori va to\'liq qamrov uchun Yordamchi.',
    'about.why.system.title': 'Ikki Yo\'nalishli Tizim',
    'about.why.system.description': 'Universitetlaringizni tanlang yoki 100% qaytarim kafolati bilan bizning tanlovimizga ishoning.',
    'about.why.support.title': 'To\'liq Qo\'llab-quvvatlash',
    'about.why.support.description': '1-Avgustdan yakuniy qarorgacha, barcha 16 ta chek-list bandlarini qamrab oladi.',
    'about.why.success.title': 'Isbotlangan Muvaffaqiyat',
    'about.why.success.description': 'Talabalar UChicago, Duke, Carnegie Mellon Qatar kabi top universitetlarga qabul bo\'lishdi.',
    'about.stats.viewers': 'Podcast Ko\'ruvchilari',
    'about.stats.sat': 'O\'rtacha SAT Bali',
    'about.stats.founded': 'Toshkentda Tashkil Etilgan',
    
    // Testimonials section
    'testimonials.title': 'Muvaffaqiyat',
    'testimonials.title.highlight': 'hikoyalari',
    'testimonials.subtitle': 'Bizning Accepted dasturi orqali ta\'lim yo\'llarini o\'zgartirib, orzulariga erishgan talabalarimizning hikoyalarini eshiting.',
    
    // FAQ section
    'faq.title': 'Ko\'p beriladigan',
    'faq.title.highlight': 'savollar',
    'faq.subtitle': 'Bizning Accepted dasturi haqida eng ko\'p soraladigan savollarga javoblar.',
    'faq.q1.question': 'Kimlar Accepted dasturiga kirishi mumkin?',
    'faq.q1.answer': 'Bizning dastur oliy ta\'limni jiddiy ko\'radigan barcha talabalarga ochiq. Qishloq yoki shahardan bo\'lishingizdan qat\'iy nazar, dasturimiz har qanday fonda muvaffaqiyat qozonishingizga yordam beradi.',
    'faq.q2.question': 'Bu dastur bepul manbalardan nimasi bilan farq qiladi?',
    'faq.q2.answer': 'Biz bepul ta\'limga ishonamiz, lekin Accepted dasturi shaxsiy mentorlik, jonli interaktiv sessiyalar, to\'liq o\'quv materiallari, test sinovlari va bepul manbalarda topilmaydigan individual yo\'l-yo\'riqni taklif qiladi.',
    'faq.q3.question': 'Dasturni tugatish uchun qancha vaqt kerak?',
    'faq.q3.answer': 'To\'liq dastur 16 hafta davom etadi, haftada 3 ta sessiya bilan. Har bir sessiya oldingi ustiga quriladi va qabul maqsadlaringiz uchun to\'liq tayyorgarlikni ta\'minlaydi.',
    'faq.q4.question': 'To\'lov rejalari yoki stipendiyalar bormi?',
    'faq.q4.answer': 'Ha! Biz moslashuvchan to\'lov rejalarini va moliyaviy ehtiyojini ko\'rsatgan talabalar uchun ehtiyojga asoslangan stipendiyalarni taklif qilamiz. Maqsadimiz sifatli ta\'limni hammaga ochiq qilish.',
    'faq.q5.question': 'Dasturdan norozi bo\'lsam, nima bo\'ladi?',
    'faq.q5.answer': 'Biz 30 kunlik pul qaytarish kafolatini taklif qilamiz. Agar dastlabki 30 kun ichida dasturdan to\'liq norozi bo\'lsangiz, hech qanday savol berilmagan holda to\'liq qaytarib beramiz.',
    'faq.q6.question': 'Dastur tugagandan so\'ng ham yordam olamanmi?',
    'faq.q6.answer': 'Albatta! Sizda bizning bitiruvchilar tarmog\'iga, kurs materiallariga umrbod kirish huquqi bo\'ladi va qo\'shimcha mentorlik sessiyalarini belgilashingiz mumkin. Biz sizning uzoq muddatli muvaffaqiyatingizga sodiqmiz.',
    'faq.q7.question': 'Mashg\'ulotlar qay tartibda va qayerda o\'tkaziladi?',
    'faq.q7.answer': 'Jonli sessiyalar bizning ta\'lim platformamiz orqali onlayn o\'tkaziladi. Ular interaktiv bo\'lib, real vaqtda savol berishingizga imkon beradi. Barcha sessiyalar yozib olinadi, shuning uchun keyinroq ko\'rib chiqishingiz mumkin.',
    'faq.q8.question': 'Dastur uchun qanday texnik qurilma kerak?',
    'faq.q8.answer': 'Sizga internet ulanishi bo\'lgan kompyuter yoki planshet kerak bo\'ladi. Bizning platformamiz barcha zamonaviy brauzerlarda ishlaydi va to\'liq ishtirok etishingizni ta\'minlash uchun texnik yordam beramiz.',
    
    // Course Details section
    'course.title': 'to\'liq qabul paketi',
    'course.title.highlight': 'Accepted',
    'course.subtitle': '"Accepted" dasturi orqali siz uch mutaxassis — strateg, insho yozish bo\'yicha mentor hamda qabul jarayonida ko\'maklashuvchi xodim bilan ishlash imkoniyatiga ega bo\'lasiz.',
    'course.team.title': 'Sening mutaxassis jamoyaing',
    'course.team.strategist': 'Strateg',
    'course.team.strategist.description': 'Ariza strategiyasini boshqaradi, universitetlar ro\'yxatini tuzadi, vaqt jadvalingizga qarab darslar rejalashtiradi.',
    'course.team.essay': 'Insho yozish bo\'yicha mentor',
    'course.team.essay.description': 'Shaxsiy g\'oyangizni ta\'sirli inshoga aylantirish, loyihalash va tahrirlashda yordam beradi.',
    'course.team.helper': 'Yordamchi',
    'course.team.helper.description': 'Ariza shakllari, moliyaviy hujjatlar, eslatmalar va boshqa texnik vazifalar bilan yordam beradi.',
    'course.details.title': 'Dastur tafsilotlari',
    'course.details.duration': 'Davomiyligi',
    'course.details.duration.value': '1-avg - yakuniy qarorlar',
    'course.details.team': 'Jamoa hajmi',
    'course.details.team.value': 'Har talaba uchun 3 mutaxassis',
    'course.details.universities': 'Universitetlar',
    'course.details.universities.value': '5 ta maqsadli maktab',
    'course.details.support': 'Yordam turi',
    'course.details.support.value': 'To\'liq ariza',
    'course.details.checklist': '16 bandli talaba chek-listi:',
    'course.pricing.badge': 'Arizalar Ochiq',
    'course.pricing.title': 'Accepted dasturi',
    'course.pricing.contact': 'Aloqa',
    'course.pricing.price': 'Narx uchun',
    'course.pricing.custom': 'Sening ehtiyojlaringga qarab moslashtirilgan',
    'course.pricing.apply': 'Hoziroq ariza ber',
    'course.pricing.consultation': 'Maslahat vaqti belgilay',
    'course.pricing.guarantee': '🛡️ 100% pul qaytarim kafolati mavjud • Premium yordam',
    
    // Footer section
    'footer.description': 'UNLOCK UZBEKISTAN - o\'zbek talabalariga xalqaro universitetlarga kirishda yordam beruvchi tashkilot. Bizning maqsadimiz har bir talabaning orzularini amalga oshirishga yordam berish.',
    'footer.quicklinks': 'Tezkor linklar',
    'footer.quicklinks.about': 'Biz haqimizda',
    'footer.quicklinks.accepted': 'Accepted dasturi',
    'footer.quicklinks.testimonials': 'Muvaffaqiyat hikoyalari',
    'footer.quicklinks.contact': 'Aloqa',
    'footer.quicklinks.blog': 'Blog',
    'footer.support': 'Yordam',
    'footer.support.center': 'Yordam markazi',
    'footer.support.portal': 'Talaba portali',
    'footer.support.payments': 'To\'lov usullari',
    'footer.support.scholarships': 'Stipendiyalar',
    'footer.support.technical': 'Texnik yordam',
    'footer.newsletter': 'Yangiliklardan xabardor bo\'l',
    'footer.newsletter.description': 'Dasturlar va ta\'lim imkoniyatlari haqida yangiliklarni birinchi bo\'lib bilish uchun obuna bo\'l.',
    'footer.newsletter.placeholder': 'Email adresingiz',
    'footer.newsletter.spam': 'Spam yo\'q. Istalgan vaqtda obunani bekor qiling.',
    'footer.copyright': '© 2024 Unlock Uzbekistan. Barcha huquqlar himoyalangan.',
    'footer.privacy': 'Maxfiylik siyosati',
    'footer.terms': 'Foydalanish shartlari',
    'footer.cookies': 'Cookie siyosati',
  },
  ru: {
    // Hero section
    'hero.title': 'Поступи в',
    'hero.title.accepted': 'Университет мечты!',
    'hero.subtitle': 'Получи самый полный пакет поступления от UNLOCK UZBEKISTAN. Работай с 3 специалистами: Стратегом, Наставником по эссе и Помощником. Выбери наш отбор университетов или получи 100% возврат денег.',
    'hero.cta': 'Подать заявку в Accepted',
    'hero.consultation': 'Записаться на консультацию',
    'hero.feature1': '3 специалиста для каждого студента',
    'hero.feature2': '100% Гарантия возврата денег*',
    'hero.feature3': 'Полная помощь с заявкой',
    'hero.feature4': 'С 1 августа до финального решения',
    'hero.card.text': 'Подача заявок начинается',
    'hero.card.cta': 'Начать',
    
    // Contact form
    'contact.title.accepted': 'ACCEPTED',
    'contact.title.text': 'Подать заявку',
    'contact.subtitle': 'Готов работать с 3 специалистами для поступления в университет мечты? Начни подачу заявки сегодня или запишись на консультацию.',
    'contact.form.title': 'Подать заявку в программу Accepted',
    'contact.form.name': 'Имя',
    'contact.form.surname': 'Фамилия',
    'contact.form.email': 'Email',
    'contact.form.phone': 'Номер телефона',
    'contact.form.major': 'Специальность или интересы',
    'contact.form.education': 'Текущий статус образования',
    'contact.form.universities': 'Список 5 университетов для поступления',
    'contact.form.contribution': 'Годовой вклад в университет',
    'contact.form.comment': 'Дополнительный комментарий',
    'contact.form.submit': 'Отправить заявку',
    'contact.form.submitting': 'Отправка...',
    'contact.form.placeholder.name': 'Ваше имя',
    'contact.form.placeholder.surname': 'Ваша фамилия',
    'contact.form.placeholder.email': 'your.email@example.com',
    'contact.form.placeholder.phone': '+998 90 123 45 67',
    'contact.form.placeholder.major': 'например: Информатика, Медицина, Бизнес',
    'contact.form.placeholder.education': 'например: 11 класс, Выпускник школы, Перевод из университета',
    'contact.form.placeholder.universities': 'Перечислите ваши топ-5 университетов...',
    'contact.form.placeholder.contribution': 'например: $50,000, Нужна полная стипендия и т.д.',
    'contact.form.placeholder.comment': 'Расскажите о вашем академическом прошлом, внеклассной деятельности и целях...',
    'contact.info.location.title': 'Наше местоположение',
    'contact.info.location.address': 'Ташкент, Узбекистан',
    'contact.info.location.description': 'Главный офис UNLOCK UZBEKISTAN. Мы обслуживаем студентов по всей стране, которые хотят поступать в университеты США, Великобритании, Европы и Азии.',
    'contact.info.phone.title': 'Телефон',
    'contact.info.phone.number': '+998 90 123 45 67',
    'contact.info.phone.description': 'Позвоните нам, чтобы записаться на консультацию по программе Accepted.',
    'contact.info.email.title': 'Email',
    'contact.info.email.address': 'accepted@unlocku.uz',
    'contact.info.email.description': 'Отправьте нам ваши вопросы о поступлении по email, и мы ответим в течение 24 часов.',
    'contact.info.hours.title': 'Рабочие часы',
    'contact.info.hours.time': 'Пн - Пт: 9:00 - 18:00',
    'contact.info.hours.description': 'Мы доступны в рабочие часы для консультаций и помощи с заявками.',
    'contact.cta.title': 'Готов поступить?',
    'contact.cta.description': 'Подача заявок начинается 1 августа 2025. Получи приоритетную консультацию с ранними советами.',
    'contact.cta.button': 'Получить приоритетный доступ',
    'contact.form.error.required': 'Пожалуйста, заполните все обязательные поля.',
    'contact.form.error.submit': 'Ошибка отправки заявки. Попробуйте еще раз.',
    'contact.form.success.title': 'Успех!',
    'contact.form.success.description': 'Ваша заявка отправлена! Мы свяжемся с вами в течение 24 часов.',
    
    // Navigation
    'nav.about': 'О нас',
    'nav.courses': 'Курсы',
    'nav.testimonials': 'Истории успеха',
    'nav.faq': 'Вопросы',
    'nav.contact': 'Контакты',
    
    // Common
    'common.loading': 'Загрузка...',
    'common.error': 'Ошибка',
    'common.success': 'Успех',
    
    // About section
    'about.title': 'О',
    'about.title.highlight': 'UNLOCK UZBEKISTAN',
    'about.subtitle': 'Основана в Ташкенте в 2022 году. Мы начали с подкастов с узбекскими студентами, поступившими в университеты Лиги Плюща. Теперь мы предлагаем комплексную помощь в поступлении через нашу программу "Accepted" с более чем 50,000 зрителей.',
    'about.values.mission.title': 'Наша миссия',
    'about.values.mission.description': 'Помочь узбекским студентам экспертным руководством и проверенными стратегиями для поступления в международные университеты.',
    'about.values.story.title': 'Наша история',
    'about.values.story.description': 'Начав с подкастов с студентами, поступившими в университеты Лиги Плюща, теперь мы поддерживаем студентов полным спектром услуг по поступлению.',
    'about.values.impact.title': 'Влияние на сообщество',
    'about.values.impact.description': 'Более 50,000 зрителей доверяют нашему контенту. Мы помогли студентам поступить в Чикаго, Дюк, Карнеги-Меллон Катар и NYU.',
    'about.values.approach.title': 'Наш подход',
    'about.values.approach.description': 'Три специалиста для каждого студента: Стратег для планирования, Наставник по эссе для написания и Помощник для технической поддержки.',
    'about.why.title': 'Почему выбрать Accepted?',
    'about.why.expert.title': 'Команда экспертов',
    'about.why.expert.description': 'Работайте с 3 специалистами - Стратегом, Наставником по эссе и Помощником для полного охвата.',
    'about.why.system.title': 'Двухтрековая система',
    'about.why.system.description': 'Выберите свои университеты или доверьтесь нашему выбору со 100% гарантией возврата денег.',
    'about.why.support.title': 'Полная поддержка',
    'about.why.support.description': 'С 1 августа до финальных решений, охватывая все 16 пунктов чек-листа.',
    'about.why.success.title': 'Проверенный успех',
    'about.why.success.description': 'Студенты были приняты в топовые университеты, такие как UChicago, Duke, Carnegie Mellon Qatar.',
    'about.stats.viewers': 'Зрители подкаста',
    'about.stats.sat': 'Средний балл SAT',
    'about.stats.founded': 'Основана в Ташкенте',
    
    // Testimonials section
    'testimonials.title': 'Истории',
    'testimonials.title.highlight': 'успеха',
    'testimonials.subtitle': 'Послушайте истории наших студентов, которые изменили свои образовательные пути и достигли своих мечт через нашу программу Accepted.',
    
    // FAQ section
    'faq.title': 'Часто',
    'faq.title.highlight': 'задаваемые вопросы',
    'faq.subtitle': 'Ответы на самые часто задаваемые вопросы о нашей программе Accepted.',
    'faq.q1.question': 'Кто может присоединиться к программе Accepted?',
    'faq.q1.answer': 'Наша программа открыта для всех студентов, серьезно относящихся к высшему образованию. Независимо от того, из сельской или городской местности вы, наша программа поможет вам добиться успеха с любым фоном.',
    'faq.q2.question': 'Чем это отличается от бесплатных ресурсов?',
    'faq.q2.answer': 'Мы верим в бесплатное образование, но программа Accepted предлагает персональное наставничество, живые интерактивные сессии, комплексные учебные материалы, практические тесты и индивидуальное руководство, которого нет в бесплатных ресурсах.',
    'faq.q3.question': 'Сколько времени нужно для завершения программы?',
    'faq.q3.answer': 'Полная программа длится 16 недель с 3 сессиями в неделю. Каждая сессия строится на предыдущей и обеспечивает полную подготовку к вашим целям поступления.',
    'faq.q4.question': 'Есть ли планы оплаты или стипендии?',
    'faq.q4.answer': 'Да! Мы предлагаем гибкие планы оплаты и стипендии на основе потребностей для студентов, демонстрирующих финансовую нужду. Наша цель - сделать качественное образование доступным для всех.',
    'faq.q5.question': 'Что если я не удовлетворен программой?',
    'faq.q5.answer': 'Мы предлагаем 30-дневную гарантию возврата денег. Если вы полностью неудовлетворены программой в первые 30 дней, мы предоставим полный возврат без вопросов.',
    'faq.q6.question': 'Получу ли я помощь после окончания программы?',
    'faq.q6.answer': 'Абсолютно! У вас будет пожизненный доступ к нашей сети выпускников, курсовым материалам, и вы сможете планировать дополнительные сессии наставничества. Мы привержены вашему долгосрочному успеху.',
    'faq.q7.question': 'Как работают живые сессии?',
    'faq.q7.answer': 'Живые сессии проводятся онлайн через нашу обучающую платформу. Они интерактивны, позволяя вам задавать вопросы в реальном времени. Все сессии записываются, поэтому вы можете пересмотреть их позже.',
    'faq.q8.question': 'Какая технология нужна для программы?',
    'faq.q8.answer': 'Вам понадобится компьютер или планшет с интернет-соединением. Наша платформа работает во всех современных браузерах, и мы предоставляем техническую поддержку для обеспечения вашего полного участия.',
    
    // Course Details section
    'course.title': 'Полный пакет поступления',
    'course.title.highlight': 'Accepted',
    'course.subtitle': 'Наша самая комплексная программа поступления. Работайте с 3 специалистами с 1 августа до финальных решений. Выберите наш отбор университетов для 100% гарантии возврата денег.',
    'course.team.title': 'Ваша команда экспертов',
    'course.team.strategist': 'Стратег',
    'course.team.strategist.description': 'Управляет стратегией подачи документов, создает списки колледжей, планирует сроки, помогает с позиционированием и деятельностью.',
    'course.team.essay': 'Наставник по эссе',
    'course.team.essay.description': 'Помогает разрабатывать, составлять и редактировать идеи, чтобы сделать эссе четкими, личными и впечатляющими.',
    'course.team.helper': 'Помощник',
    'course.team.helper.description': 'Помогает с формами заявлений, финансовыми документами, планированием, напоминаниями и другими техническими задачами.',
    'course.details.title': 'Детали программы',
    'course.details.duration': 'Продолжительность',
    'course.details.duration.value': '1 авг - финальные решения',
    'course.details.team': 'Размер команды',
    'course.details.team.value': '3 специалиста на студента',
    'course.details.universities': 'Университеты',
    'course.details.universities.value': '5 целевых школ',
    'course.details.support': 'Тип поддержки',
    'course.details.support.value': 'Полная заявка',
    'course.details.checklist': 'Чек-лист студента из 16 пунктов:',
    'course.pricing.badge': 'Заявки открыты',
    'course.pricing.title': 'Программа Accepted',
    'course.pricing.contact': 'Связаться',
    'course.pricing.price': 'для уточнения цены',
    'course.pricing.custom': 'Адаптировано под ваши потребности',
    'course.pricing.apply': 'Подать заявку сейчас',
    'course.pricing.consultation': 'Записаться на консультацию',
    'course.pricing.guarantee': '🛡️ 100% гарантия возврата денег доступна • Премиум поддержка',
    
    // Footer section
    'footer.description': 'UNLOCK UZBEKISTAN - организация, помогающая узбекским студентам поступать в международные университеты. Наша цель - помочь каждому студенту воплотить свои мечты.',
    'footer.quicklinks': 'Быстрые ссылки',
    'footer.quicklinks.about': 'О нас',
    'footer.quicklinks.accepted': 'Программа Accepted',
    'footer.quicklinks.testimonials': 'Истории успеха',
    'footer.quicklinks.contact': 'Контакты',
    'footer.quicklinks.blog': 'Блог',
    'footer.support': 'Поддержка',
    'footer.support.center': 'Центр помощи',
    'footer.support.portal': 'Портал студентов',
    'footer.support.payments': 'Способы оплаты',
    'footer.support.scholarships': 'Стипендии',
    'footer.support.technical': 'Техническая поддержка',
    'footer.newsletter': 'Оставайтесь в курсе',
    'footer.newsletter.description': 'Подпишитесь, чтобы первыми узнавать о программах и образовательных возможностях.',
    'footer.newsletter.placeholder': 'Ваш email адрес',
    'footer.newsletter.spam': 'Никакого спама. Отписаться можно в любое время.',
    'footer.copyright': '© 2024 Unlock Uzbekistan. Все права защищены.',
    'footer.privacy': 'Политика конфиденциальности',
    'footer.terms': 'Условия использования',
    'footer.cookies': 'Политика cookies',

    // Audience Selector
    'welcomeTitle': 'Добро пожаловать',
    'audienceSelectorSubtitle': 'Выберите подходящий для вас портал',
    'studentsTitle': 'Студенты',
    'studentsDescription': 'Информация и ресурсы для студентов',
    'studentFeature1': 'Персональное руководство',
    'studentFeature2': 'Университетские программы',
    'studentFeature3': 'Помощь с заявками',
    'studentFeature4': 'Подготовка к экзаменам',
    'enterStudentPortal': 'Войти в портал студентов',
    'parentsTitle': 'Родители',
    'parentsDescription': 'Руководство и поддержка для родителей',
    'parentFeature1': 'Руководство для родителей',
    'parentFeature2': 'Финансовое планирование',
    'parentFeature3': 'Семейная поддержка',
    'parentFeature4': 'Экспертные консультации',
    'enterParentPortal': 'Войти в портал родителей',
    'notSureText': 'Не уверены? Просмотрите общую информацию',
    'viewGeneralInfo': 'Просмотреть общую информацию',

    // Student-specific content
    'studentHeroTitle': 'Ваше будущее начинается здесь',
    'studentHeroSubtitle': 'Персонализированное руководство для поступления в лучшие университеты мира',
    'studentBenefit1': 'Экспертное руководство',
    'studentBenefit2': 'Подготовка к тестам',
    'studentBenefit3': 'Глобальные возможности',
    'studentBenefit4': 'Поддержка сообщества',
    'explorePrograms': 'Изучить программы',
    'getPersonalConsultation': 'Получить консультацию',
    'studentSuccessRate': '95% успешных поступлений',
    'studentSuccessRateSubtext': 'Наши студенты поступают в топ-университеты',

    // Parent-specific content
    'parentHeroTitle': 'Поддержите будущее вашего ребенка',
    'parentHeroSubtitle': 'Комплексное руководство для родителей в процессе международного образования',
    'parentBenefit1': 'Семейная поддержка',
    'parentBenefit2': 'Финансовое планирование',
    'parentBenefit3': 'Экспертные консультации',
    'parentBenefit4': 'Отслеживание прогресса',
    'getParentGuide': 'Получить руководство',
    'speakWithExpert': 'Поговорить с экспертом',
    'parentSuccessMetric': '500+ семей доверяют нам',
    'parentSuccessMetricSubtext': 'Помогаем семьям с 2020 года',

    // Additional common translations
    'learnMore': 'Узнать больше',
    'scheduleConsultation': 'Записаться на консультацию',
    'downloadGuide': 'Скачать руководство',
    'watchWebinar': 'Смотреть вебинар',
    'accessLibrary': 'Доступ к библиотеке',
    'joinCommunity': 'Присоединиться к сообществу',
    'needPersonalizedHelp': 'Нужна персональная помощь?',
    'personalizedHelpDescription': 'Запишитесь на индивидуальную консультацию с нашими экспертами',
    'downloadCompleteGuide': 'Скачать полное руководство',
    'startChat': 'Начать чат',
    'scheduleCall': 'Запланировать звонок',
    'bookSession': 'Забронировать сессию',
    'joinGroup': 'Присоединиться к группе',
    'emergencySupport': 'Экстренная поддержка',
    'emergencySupportDesc': 'Срочная помощь доступна 24/7 для важных вопросов',
    'emergencyContact': 'Экстренный контакт',

    // Student About section
    'studentAboutTitle': 'Почему выбирают нас студенты',
    'studentAboutSubtitle': 'Мы предоставляем все необходимое для успешного поступления',
    'studentAboutFeature1Title': 'Экспертное руководство',
    'studentAboutFeature1Desc': 'Персональное сопровождение от опытных консультантов',
    'studentAboutFeature2Title': 'Индивидуальный подход',
    'studentAboutFeature2Desc': 'Программа адаптируется под ваши цели и потребности',
    'studentAboutFeature3Title': 'Поддержка сообщества',
    'studentAboutFeature3Desc': 'Присоединяйтесь к сети успешных студентов',
    'studentAboutFeature4Title': 'Гарантированный результат',
    'studentAboutFeature4Desc': '95% наших студентов поступают в целевые университеты',

    // Student Programs section
    'studentProgramsTitle': 'Наши программы для студентов',
    'studentProgramsSubtitle': 'Выберите программу, которая подходит именно вам',
    'studentProgram1Title': 'Базовая программа',
    'studentProgram1Desc': 'Основы подготовки к поступлению в международные университеты',
    'studentProgram1Duration': '3 месяца',
    'studentProgram1GroupSize': 'До 10 человек',
    'studentProgram1Level': 'Начальный',
    'studentProgram1Feature1': 'Выбор университета и специальности',
    'studentProgram1Feature2': 'Подготовка к языковым тестам',
    'studentProgram1Feature3': 'Написание мотивационного письма',
    'studentProgram1Feature4': 'Подача документов',
    'studentProgram2Title': 'Продвинутая программа',
    'studentProgram2Desc': 'Комплексная подготовка с персональным сопровождением',
    'studentProgram2Duration': '6 месяцев',
    'studentProgram2GroupSize': 'До 5 человек',
    'studentProgram2Level': 'Средний',
    'studentProgram2Feature1': 'Персональный наставник',
    'studentProgram2Feature2': 'Подготовка к SAT/TOEFL',
    'studentProgram2Feature3': 'Портфолио достижений',
    'studentProgram2Feature4': 'Мок-интервью',
    'studentProgram3Title': 'Премиум программа',
    'studentProgram3Desc': 'Полный пакет услуг для поступления в топ-университеты',
    'studentProgram3Duration': '12 месяцев',
    'studentProgram3GroupSize': 'Индивидуально',
    'studentProgram3Level': 'Продвинутый',
    'studentProgram3Feature1': 'Команда из 3 экспертов',
    'studentProgram3Feature2': 'Гарантия поступления',
    'studentProgram3Feature3': 'Подготовка к стипендиям',
    'studentProgram3Feature4': '24/7 поддержка',

    // Student Resources section
    'studentResourcesTitle': 'Ресурсы для студентов',
    'studentResourcesSubtitle': 'Все необходимые материалы в одном месте',
    'studentResource1Title': 'Руководство по поступлению',
    'studentResource1Desc': 'Пошаговая инструкция для подачи документов',
    'studentResource2Title': 'Видео-уроки',
    'studentResource2Desc': 'Обучающие материалы от экспертов',
    'studentResource3Title': 'Библиотека ресурсов',
    'studentResource3Desc': 'База знаний по университетам и программам',
    'studentResource4Title': 'Сообщество студентов',
    'studentResource4Desc': 'Общение с единомышленниками и выпускниками',

    // Parent About section
    'parentAboutTitle': 'Как мы поддерживаем родителей',
    'parentAboutSubtitle': 'Мы понимаем важность семейной поддержки в образовательном процессе',
    'parentAboutFeature1Title': 'Семейный подход',
    'parentAboutFeature1Desc': 'Работаем с семьей как единой командой',
    'parentAboutFeature2Title': 'Прозрачность процесса',
    'parentAboutFeature2Desc': 'Регулярные отчеты о прогрессе вашего ребенка',
    'parentAboutFeature3Title': 'Финансовое планирование',
    'parentAboutFeature3Desc': 'Помощь в планировании расходов на образование',
    'parentAboutFeature4Title': 'Эмоциональная поддержка',
    'parentAboutFeature4Desc': 'Психологическая помощь семье на всех этапах',

    // Parent Guide section
    'parentGuideTitle': 'Руководство для родителей',
    'parentGuideSubtitle': 'Пошаговый план поддержки вашего ребенка',
    'parentGuideStep1Title': 'Планирование и подготовка',
    'parentGuideStep1Desc': 'Определите цели и составьте план действий',
    'parentGuideStep1Duration': '1-2 месяца',
    'parentGuideStep1Task1': 'Обсуждение целей с ребенком',
    'parentGuideStep1Task2': 'Исследование университетов',
    'parentGuideStep1Task3': 'Финансовое планирование',
    'parentGuideStep2Title': 'Академическая подготовка',
    'parentGuideStep2Desc': 'Поддержите ребенка в учебном процессе',
    'parentGuideStep2Duration': '6-12 месяцев',
    'parentGuideStep2Task1': 'Мониторинг успеваемости',
    'parentGuideStep2Task2': 'Подготовка к тестам',
    'parentGuideStep2Task3': 'Развитие внеклассной деятельности',
    'parentGuideStep3Title': 'Подача документов',
    'parentGuideStep3Desc': 'Помощь в процессе подачи заявок',
    'parentGuideStep3Duration': '3-6 месяцев',
    'parentGuideStep3Task1': 'Сбор необходимых документов',
    'parentGuideStep3Task2': 'Проверка заявок',
    'parentGuideStep3Task3': 'Соблюдение дедлайнов',
    'parentGuideStep4Title': 'Принятие решения',
    'parentGuideStep4Desc': 'Поддержка в выборе лучшего предложения',
    'parentGuideStep4Duration': '1-3 месяца',
    'parentGuideStep4Task1': 'Анализ предложений',
    'parentGuideStep4Task2': 'Финансовые расчеты',
    'parentGuideStep4Task3': 'Окончательное решение',
    'parentGuideCallToAction': 'Получите полное руководство',
    'parentGuideCallToActionDesc': 'Скачайте детальный план или запишитесь на консультацию с экспертом',

    // Parent Support section
    'parentSupportTitle': 'Поддержка для родителей',
    'parentSupportSubtitle': 'Мы всегда готовы помочь вам и вашему ребенку',
    'parentSupport1Title': 'Онлайн-чат',
    'parentSupport1Desc': 'Быстрые ответы на ваши вопросы',
    'parentSupport1Availability': '24/7',
    'parentSupport2Title': 'Телефонные консультации',
    'parentSupport2Desc': 'Персональные беседы с экспертами',
    'parentSupport2Availability': 'Пн-Пт 9:00-18:00',
    'parentSupport3Title': 'Видео-консультации',
    'parentSupport3Desc': 'Детальные встречи по видеосвязи',
    'parentSupport3Availability': 'По записи',
    'parentSupport4Title': 'Групповые встречи',
    'parentSupport4Desc': 'Общение с другими родителями',
    'parentSupport4Availability': 'Еженедельно',
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('uz');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'uz' || savedLanguage === 'ru')) {
      setLanguage(savedLanguage);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};