// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qgjlpmrdswaotfrzwzeh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFnamxwbXJkc3dhb3Rmcnp3emVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3MzY1ODYsImV4cCI6MjA2ODMxMjU4Nn0.-YPqlLI6ZV_rsBzSaPEniMV3DXazh_EJyrTs33dRqTw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});